<?xml version="1.0"?>
<package format="2">
  <name>ow_ros_control_plugin</name>
  <version>0.0.0</version>
  <description>The OpenWalker bridge to tos_control</description>

  <maintainer email="rogelio.guadarrama@tum.de">J. Rogelio Guadarrama-Olvera</maintainer>
  <maintainer email="dean@tum.de">Emmanuel Dean-Leon</maintainer>
  <maintainer email="florian.bergner@tum.de">Florian Bergner</maintainer>
  <maintainer email="simon.armleder@tum.de">Simon Armleder</maintainer>

  <license>Apache 2.0</license>

  <url type="website">https://github.com/ics-robotics</url>

  <author email="rogelio.guadarrama@tum.de">J. Rogelio Guadarrama-Olvera</author>
  <author email="simon.armleder@tum.de">Simon Armleder</author>
  <author email="dean@tum.de">Emmanuel Dean-Leon</author>
  <author email="florian.bergner@tum.de">Florian Bergner</author>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>roscpp</depend>
  <depend>ow_core</depend>
  <depend>ow_hw_interface</depend>
  <depend>ow_controller</depend>
  <depend>hardware_interface</depend>
  <depend>controller_interface</depend>

  <test_depend>rosunit</test_depend>

  <!-- The export tag contains other, unspecified, tags -->
  <export>
    <controller_interface plugin="${prefix}/ow_ros_control_plugin_plugins.xml"/>
  </export>

</package>
